In [2]:
import numpy as np
import pandas as pd

In [6]:
a = np.random.randint(10,50,16)

In [7]:
a

array([16, 30, 36, 12, 19, 34, 21, 43, 10, 14, 33, 41, 33, 40, 37, 37])

In [9]:
a[-5:-7:-1]

array([41, 33])

In [31]:
np.random.seed(24)
b = np.random.randint(45,78,(7,8))
b

array([[48, 45, 68, 62, 62, 46, 60, 49],
       [63, 56, 60, 54, 63, 52, 70, 76],
       [73, 45, 57, 76, 46, 51, 62, 51],
       [46, 70, 55, 45, 72, 48, 49, 46],
       [55, 52, 50, 64, 45, 72, 66, 47],
       [77, 67, 56, 75, 66, 49, 48, 52],
       [53, 48, 51, 68, 55, 56, 61, 72]])

In [26]:
a.ndim

1

In [16]:
b.ndim

2

In [21]:
a=np.array([11,15,14,81,78,49,20,16,15,18,35,20])
a

array([11, 15, 14, 81, 78, 49, 20, 16, 15, 18, 35, 20])

In [22]:
b[:,7]  # 7 th col

array([71, 73, 55, 53, 54, 54, 65])

In [23]:
b[:,4]  # 4 th col

array([71, 66, 46, 55, 53, 72, 63])

In [34]:
b[2] # 2 nd  row

array([48, 45, 68, 62, 62, 46, 60, 49])

In [35]:
b[1,3]  # 1 row 3 col number or value or position

54

In [36]:
b[:,3]

array([62, 54, 76, 45, 64, 75, 68])

In [37]:
b

array([[48, 45, 68, 62, 62, 46, 60, 49],
       [63, 56, 60, 54, 63, 52, 70, 76],
       [73, 45, 57, 76, 46, 51, 62, 51],
       [46, 70, 55, 45, 72, 48, 49, 46],
       [55, 52, 50, 64, 45, 72, 66, 47],
       [77, 67, 56, 75, 66, 49, 48, 52],
       [53, 48, 51, 68, 55, 56, 61, 72]])

In [39]:
b[2,1:7]   #  row = left part
           # here 2 is row 
           # here start position is 1 and 7 is end position in row

###array [ row _start : row-end: row - step ]

array([45, 57, 76, 46, 51, 62])

In [41]:
b [1:6:2]  # array[row_start:row_end - step ]

array([[63, 56, 60, 54, 63, 52, 70, 76],
       [46, 70, 55, 45, 72, 48, 49, 46],
       [77, 67, 56, 75, 66, 49, 48, 52]])

In [48]:
b [1:6:2,1:6]     # array[row_start:row_end - step ,col_start: col_end : step]

array([[56, 60, 54, 63, 52],
       [70, 55, 45, 72, 48],
       [67, 56, 75, 66, 49]])

In [60]:
b[1:6:2,1:8:2]     # array[row_start:row_end - step ,col_start: col_end : step]

#left side row operations
#right side col operations

array([[56, 54, 52, 76],
       [70, 45, 48, 46],
       [67, 75, 49, 52]])

In [55]:
b

array([[48, 45, 68, 62, 62, 46, 60, 49],
       [63, 56, 60, 54, 63, 52, 70, 76],
       [73, 45, 57, 76, 46, 51, 62, 51],
       [46, 70, 55, 45, 72, 48, 49, 46],
       [55, 52, 50, 64, 45, 72, 66, 47],
       [77, 67, 56, 75, 66, 49, 48, 52],
       [53, 48, 51, 68, 55, 56, 61, 72]])